defaults:
  - dataset: single_stonk
  - model: simple_rnn
  - model/backbone: lstm
  - criterion: pnl

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d-%H:%M:%S}_${hydra.job.config_name}_${hydra.job.override_dirname}

dataloader:
  batch_size: 256
  num_workers: 12

random_seed: 0

optim:
  lr: 0.0001
  num_epochs: 1000
clip_grad_norm: 1

weights:

display:
  logdir: 'summary'
  iprint: 10
