data:
  dataset:
    name: 'SingleStonkDataset'
    feature_size: 5
    sequence_length: 1000
  batch_size: 128
  num_workers: 4

model: 
  name: 'simplemodel'
  backbone: 
    name: 'lstm'
    input_size: 5       # Should match data.dataset.feature_size
    hidden_size: 256
    num_layers: 256
    batch_first: True
  readout: 
    # Create an MLP with these parameters.
    output_size: 1
    hidden_size: 256
    num_layers: 0

criterion:
  name: 'sharpecriterion'

random_seed: 0

optim:
  lr: 0.0001
  num_epochs: 1000

weights:

display:
  iprint: 100
